### PR TITLE
Directory option

### LINKED ISSUE #52: add -C/--directory option
In most cases, the we want to use gepetuto on the current working directory. But sometimes, like in the unit tests of this repo, we need to ask it to run from another one. This is what the `-C` / `--directory` option is usually for.

So we should add it, and use it as the first part of all the `Path()` we have.

Then, we'll be able to add `-C tests` in `.pre-commit-config.yaml`.

### PR DESCRIPTION
**Pull request by TheoMF**
fix #52

### CODE REVIEW

**Review by nim65s — COMMENTED** [review]
I'm not sure if we really need to change this tp_id in tp_ids, but this should work.
Could you enable the test of this, by replacing the `cd` in the CI ?

**Comment by TheoMF** [comment]
> I'm not sure if we really need to change this tp_id in tp_ids, but this should work. Could you enable the test of this, by replacing the `cd` in the CI ?

I used tp_ids because when calling the generate function, he says there are two variables called tp_id and return an error. But we can modify directly the tp_id in `args` after the call to `parse_args()` and keep tp_id if you prefer like that

**Comment by nim65s** [comment]
Ok, now I understand, thanks. And this comes from the fact that we can't put `get_tp_ids` the `default` argument anymore, because it is now requiring an argument which depend on the `--directory` option.

Another solution would be to use [`chdir(args.directory)`](https://docs.python.org/3.11/library/os.html#os.chdir) directly after the first `args = parse_args()` if `directory` was set by the user, and afterwards do another `args = parse_args()`.

Could you try this other method, in another PR, so that we can compare both solutions ?

**Comment by TheoMF** [comment]
> Ok, now I understand, thanks. And this comes from the fact that we can't put `get_tp_ids` the `default` argument anymore, because it is now requiring an argument which depend on the `--directory` option.
> 
> Another solution would be to use [`chdir(args.directory)`](https://docs.python.org/3.11/library/os.html#os.chdir) directly after the first `args = parse_args()` if `directory` was set by the user, and afterwards do another `args = parse_args()`.
> 
> Could you try this other method, in another PR, so that we can compare both solutions ?

it's a lot shorter !

**Comment by nim65s** [comment]
Fixed by #57

**Pull request closed without merging**
